import {
  COORD_LIMIT,
  MAX_ARENA_EXTENT,
  PROJECTILE_BOUNDS_MARGIN,
  isInsideBounds
} from "../schema/arena";
import type { EditorArena } from "../state/editorState";

/**
 * The game's shipped-arena geometry rules
 * (`shared/src/schemas/shippedArenaGeometry.test.ts`), reimplemented as a pure
 * function over the editor model.
 *
 * WHY this lives in the builder: the zod schema in src/schema/arena.ts only
 * catches what a single field can express (wire limits, unit sun vectors).
 * Everything below is *relational* — rock vs rock, rock vs corridor, rock vs
 * bounds — so the game enforces it in a CI test instead. Without this module a
 * map author only discovers a violation after exporting, copying into the game
 * repo and running its suite; here they see it while they are still dragging
 * the rock.
 *
 * Everything is reported rather than thrown: an author mid-edit is *expected*
 * to be transiently invalid, so the caller gets a list it can render next to
 * the offending placement, and a single `ok` flag for "would the game's CI take
 * this".
 *
 * Coordinate system matches the rest of the project: Babylon left-handed, Y up.
 */

/**
 * Collider radii of the shipped rock palette at scale 1.
 *
 * Collision in Space Arena is *always* a sphere (asteroid.collider.radius ×
 * placement.scale) no matter how irregular the mesh looks, so a single number
 * per asteroid id is the whole collision story — see
 * docs/space-arena-import-reference.md §3. Exported because the viewport wants
 * the same numbers to draw collider bubbles, and a second copy would drift.
 */
export const ASTEROID_COLLIDER_RADII: Readonly<Record<string, number>> = {
  "asteroid.colossal-a": 18,
  "asteroid.colossal-b": 18,
  "asteroid.large-hazard": 8,
  "asteroid.large-hazard-b": 8,
  "asteroid.small-rock": 3.5,
  "asteroid.small-rock-b": 3.5
};

/** Minimum surface clearance between a rock and the spawn-to-spawn corridor. */
export const MIN_CORRIDOR_CLEARANCE = 25;

/**
 * Minimum surface distance between a centrepiece rock and any spawn pad.
 *
 * The CI gate is class-dependent: 25 for an ordinary rock, 30 for a
 * colossal-class one (docs/MAP-DESIGN-PROMPT.md rule 3, and "≥ 25 units of
 * clearance between a big centrepiece and any spawn pad" in
 * docs/space-arena-import-reference.md §3).
 *
 * The design prompt also tells map *authors* to "use 30 everywhere to be safe".
 * That is authoring guidance, not the gate — so a non-colossal centrepiece
 * landing between the two numbers is reported as a warning here, never an
 * error. Charging every centrepiece the colossal 30 would make the builder
 * refuse maps the game's own CI accepts, which is the one thing a pre-flight
 * validator must never do.
 */
export const MIN_CENTREPIECE_SPAWN_CLEARANCE = 25;

/** Rule 3's stricter gate for colossal-class rocks; also the recommended value. */
export const MIN_COLOSSAL_SPAWN_CLEARANCE = 30;

/** Minimum surface gap between any two rocks. */
export const MIN_ROCK_SEPARATION = 12;

/**
 * The volumetric rule's two halves: rocks must reach at least this far above
 * AND below the equator, and at least one must sit this far off it.
 */
export const VOLUMETRIC_SPAN = 25;
export const VOLUMETRIC_PEAK = 35;

/**
 * Tolerance for the mirror-symmetry twin search. Authors type coordinates like
 * 38.15, and a twin generated by negating x is exact, so this only has to
 * absorb float noise — not sloppy hand-placement.
 */
export const MIRROR_EPSILON = 1e-3;

export type Severity = "error" | "warning" | "info";

export interface Diagnostic {
  /**
   * Stable machine-readable rule id — the UI groups and filters on this, so
   * these strings are API and must not be reworded casually.
   */
  rule: string;
  severity: Severity;
  /**
   * Human-readable, and always carrying the concrete numbers: an author has to
   * be able to fix the map from the message alone, without re-deriving the
   * arithmetic the validator just did.
   */
  message: string;
  /** Indices into `arena.asteroidPlacements` implicated by this diagnostic. */
  placementIndices?: number[];
  /** Ids of spawn points implicated by this diagnostic. */
  spawnIds?: string[];
}

export interface GeometryStats {
  rockCount: number;
  /** Rocks whose collider overlaps the origin (|P| < r) — corridor-exempt. */
  centrepieceCount: number;
  /** Placements whose asteroid id is not in the shipped palette. */
  unknownAsteroidCount: number;
  /** Smallest rock-to-rock surface gap; null with fewer than two sized rocks. */
  minSurfaceGap: number | null;
  /** Largest |P| + r across sized rocks; null when there are none. */
  maxExtent: number | null;
  /** Sphere radius to compare `maxExtent` against; null for rect bounds. */
  boundsRadius: number | null;
  /** Placement y range; null when the map has no placements. */
  yMin: number | null;
  yMax: number | null;
  /** Distinct teams owning at least one spawn point. */
  teamCount: number;
}

export interface GeometryReport {
  /** True when no diagnostic has severity "error". */
  ok: boolean;
  /** Errors first, then warnings, then info; stable within each severity. */
  diagnostics: Diagnostic[];
  stats: GeometryStats;
}

interface Vec3 {
  x: number;
  y: number;
  z: number;
}

interface Rock {
  index: number;
  asteroidId: string;
  position: Vec3;
  /** collider radius × scale, or null when the asteroid id is unknown */
  radius: number | null;
}

/** A rock with a known radius — the only kind the metric rules can judge. */
interface SizedRock extends Rock {
  radius: number;
}

interface Corridor {
  teamA: number;
  teamB: number;
  a: Vec3;
  b: Vec3;
  spawnIds: string[];
}

const SEVERITY_ORDER: Record<Severity, number> = { error: 0, warning: 1, info: 2 };

/**
 * Round for display only. Trailing zeros are dropped so whole coordinates read
 * as "(70, 45, 0)" rather than "(70.00, 45.00, 0.00)" — messages are prose an
 * author scans, not a data format.
 */
function fmt(value: number): string {
  return String(Math.round(value * 100) / 100);
}

function point(p: Vec3): string {
  return `(${fmt(p.x)}, ${fmt(p.y)}, ${fmt(p.z)})`;
}

function length(p: Vec3): number {
  return Math.hypot(p.x, p.y, p.z);
}

function distance(a: Vec3, b: Vec3): number {
  return Math.hypot(a.x - b.x, a.y - b.y, a.z - b.z);
}

/**
 * Distance from a point to a *segment*, not to the infinite line through it.
 * The projection parameter is clamped to [0, 1] because a rock parked behind a
 * team's spawn line is nowhere near the lane between the two spawns even
 * though the extended line runs straight through it — an unclamped version
 * would flag every rim rock on a symmetric map.
 */
function distancePointToSegment(p: Vec3, a: Vec3, b: Vec3): number {
  const abx = b.x - a.x;
  const aby = b.y - a.y;
  const abz = b.z - a.z;
  const lengthSq = abx * abx + aby * aby + abz * abz;
  if (lengthSq === 0) return distance(p, a);
  const raw = ((p.x - a.x) * abx + (p.y - a.y) * aby + (p.z - a.z) * abz) / lengthSq;
  const t = Math.min(1, Math.max(0, raw));
  return Math.hypot(p.x - (a.x + t * abx), p.y - (a.y + t * aby), p.z - (a.z + t * abz));
}

/** Positions carry an optional y (the schema defaults it to 0). */
function toVec3(p: { x: number; y?: number | undefined; z: number }): Vec3 {
  return { x: p.x, y: p.y ?? 0, z: p.z };
}

/**
 * A rock whose collider swallows the origin is the map's centrepiece: it is
 * *meant* to sit in the middle of the fight, so the corridor rule exempts it
 * (rule 3 charges it a spawn-clearance minimum instead).
 */
function isCentrepiece(rock: SizedRock): boolean {
  return length(rock.position) < rock.radius;
}

/**
 * Colossal-class rocks carry rule 3's stricter 30-unit spawn clearance. Matched
 * on the id prefix rather than the radius so a heavily scaled large-hazard is
 * still judged as the mid-size rock it is, exactly as the game's palette
 * classifies it.
 */
function isColossalClass(asteroidId: string): boolean {
  return asteroidId.startsWith("asteroid.colossal");
}

/**
 * Floored arenas ("crater" maps) declare a ground plane the game builds the
 * bowl on. Our zod mirror does not model `floorY` yet, so read it structurally
 * rather than pretend a map cannot have one — getting this wrong turns a
 * legitimately one-sided map into a false volumetric failure.
 */
function readFloorY(bounds: EditorArena["bounds"]): number | null {
  const raw = (bounds as { floorY?: unknown }).floorY;
  return typeof raw === "number" && Number.isFinite(raw) ? raw : null;
}

/**
 * Effective collider radius of a placement, or null when the asteroid id is
 * not in the shipped palette. Null rather than a guessed default: inventing a
 * radius would make every downstream rule quietly wrong, and the docs
 * explicitly allow a map to ship its own asteroid.* config.
 */
function effectiveRadius(asteroidId: string, scale: number | undefined): number | null {
  const base = ASTEROID_COLLIDER_RADII[asteroidId];
  if (base === undefined) return null;
  return base * (scale ?? 1);
}

function collectRocks(arena: EditorArena): Rock[] {
  return arena.asteroidPlacements.map((p, index) => ({
    index,
    asteroidId: p.asteroidId,
    position: toVec3(p.position),
    radius: effectiveRadius(p.asteroidId, p.scale)
  }));
}

function isSized(rock: Rock): rock is SizedRock {
  return rock.radius !== null;
}

function describe(rock: Rock): string {
  return `rock ${rock.index} (${rock.asteroidId}) at ${point(rock.position)}`;
}

/**
 * One corridor per unordered pair of teams. Two teams is the normal case and
 * reduces to the single spawn-to-spawn segment the game's test uses; handling
 * N teams generally costs nothing and avoids silently ignoring lanes on a
 * three-way map.
 */
function buildCorridors(arena: EditorArena): { corridors: Corridor[]; teamCount: number } {
  const byTeam = new Map<number, { positions: Vec3[]; spawnIds: string[] }>();
  for (const sp of arena.spawnPoints) {
    let entry = byTeam.get(sp.team);
    if (!entry) {
      entry = { positions: [], spawnIds: [] };
      byTeam.set(sp.team, entry);
    }
    entry.positions.push(toVec3(sp.position));
    entry.spawnIds.push(sp.id);
  }

  const teams = [...byTeam.keys()].sort((a, b) => a - b);
  const centroids = new Map<number, Vec3>();
  for (const team of teams) {
    const entry = byTeam.get(team);
    if (!entry) continue;
    const n = entry.positions.length;
    centroids.set(team, {
      x: entry.positions.reduce((s, p) => s + p.x, 0) / n,
      y: entry.positions.reduce((s, p) => s + p.y, 0) / n,
      z: entry.positions.reduce((s, p) => s + p.z, 0) / n
    });
  }

  const corridors: Corridor[] = [];
  for (let i = 0; i < teams.length; i++) {
    for (let j = i + 1; j < teams.length; j++) {
      const teamA = teams[i];
      const teamB = teams[j];
      if (teamA === undefined || teamB === undefined) continue;
      const a = centroids.get(teamA);
      const b = centroids.get(teamB);
      const entryA = byTeam.get(teamA);
      const entryB = byTeam.get(teamB);
      if (!a || !b || !entryA || !entryB) continue;
      corridors.push({
        teamA,
        teamB,
        a,
        b,
        spawnIds: [...entryA.spawnIds, ...entryB.spawnIds]
      });
    }
  }

  return { corridors, teamCount: teams.length };
}

function checkWireLimit(arena: EditorArena, out: Diagnostic[]): void {
  const bounds = arena.bounds;
  const extent =
    bounds.shape === "sphere"
      ? bounds.radius
      : Math.max(bounds.width, bounds.height, bounds.verticalExtent) / 2;
  const label = bounds.shape === "sphere" ? "bounds radius" : "largest bounds half-extent";
  if (extent > MAX_ARENA_EXTENT) {
    out.push({
      rule: "wire-limit",
      severity: "error",
      message:
        `${label} ${fmt(extent)} + projectile margin ${PROJECTILE_BOUNDS_MARGIN} = ` +
        `${fmt(extent + PROJECTILE_BOUNDS_MARGIN)} exceeds the ±${COORD_LIMIT} wire limit; ` +
        `keep the extent at or under ${fmt(MAX_ARENA_EXTENT)}`
    });
  }
}

function checkExtent(arena: EditorArena, rocks: SizedRock[], out: Diagnostic[]): void {
  const bounds = arena.bounds;
  if (bounds.shape !== "sphere") {
    out.push({
      rule: "extent",
      severity: "info",
      message:
        "extent checking is sphere-only; this arena uses rect bounds, so rule 1 " +
        "(|P| + r <= R) was skipped"
    });
    return;
  }
  for (const rock of rocks) {
    const reach = length(rock.position) + rock.radius;
    if (reach > bounds.radius) {
      out.push({
        rule: "extent",
        severity: "error",
        message:
          `${describe(rock)}: reaches ${fmt(reach)} from the centre ` +
          `(|P| ${fmt(length(rock.position))} + r ${fmt(rock.radius)}), ` +
          `bounds radius is ${fmt(bounds.radius)} — over by ${fmt(reach - bounds.radius)}`,
        placementIndices: [rock.index]
      });
    }
  }
}

function checkCorridor(corridors: Corridor[], rocks: SizedRock[], out: Diagnostic[]): void {
  for (const rock of rocks) {
    if (isCentrepiece(rock)) continue;

    let worst: { corridor: Corridor; clearance: number } | null = null;
    for (const corridor of corridors) {
      const clearance =
        distancePointToSegment(rock.position, corridor.a, corridor.b) - rock.radius;
      if (!worst || clearance < worst.clearance) worst = { corridor, clearance };
    }
    if (!worst || worst.clearance >= MIN_CORRIDOR_CLEARANCE) continue;

    const { corridor, clearance } = worst;
    out.push({
      rule: "corridor",
      severity: "error",
      message:
        `${describe(rock)}: surface clearance ${fmt(clearance)} to the spawn corridor ` +
        `between teams ${corridor.teamA} and ${corridor.teamB} ` +
        `(${point(corridor.a)} → ${point(corridor.b)}), needs >= ${MIN_CORRIDOR_CLEARANCE}`,
      placementIndices: [rock.index],
      spawnIds: corridor.spawnIds
    });
  }
}

function checkCentrepieceClearance(
  arena: EditorArena,
  rocks: SizedRock[],
  out: Diagnostic[]
): void {
  for (const rock of rocks) {
    if (!isCentrepiece(rock)) continue;
    const colossal = isColossalClass(rock.asteroidId);
    const gate = colossal
      ? MIN_COLOSSAL_SPAWN_CLEARANCE
      : MIN_CENTREPIECE_SPAWN_CLEARANCE;
    for (const sp of arena.spawnPoints) {
      const surface = distance(rock.position, toVec3(sp.position)) - rock.radius;
      const where =
        `surface distance ${fmt(surface)} to spawn "${sp.id}" at ` +
        `${point(toVec3(sp.position))}`;
      if (surface < gate) {
        out.push({
          rule: "centrepiece-clearance",
          severity: "error",
          message:
            `centrepiece ${describe(rock)}: ${where}, needs >= ${gate}` +
            `${colossal ? " (colossal-class)" : ""}`,
          placementIndices: [rock.index],
          spawnIds: [sp.id]
        });
      } else if (surface < MIN_COLOSSAL_SPAWN_CLEARANCE) {
        // Clears the gate for its class but sits under the value the design
        // prompt tells authors to use everywhere. Advisory, so `ok` stays true.
        out.push({
          rule: "centrepiece-clearance",
          severity: "warning",
          message:
            `centrepiece ${describe(rock)}: ${where} — clears rule 3's ` +
            `${MIN_CENTREPIECE_SPAWN_CLEARANCE} for a non-colossal rock, but the design ` +
            `guide recommends ${MIN_COLOSSAL_SPAWN_CLEARANCE} everywhere`,
          placementIndices: [rock.index],
          spawnIds: [sp.id]
        });
      }
    }
  }
}

function checkSeparation(
  rocks: SizedRock[],
  out: Diagnostic[]
): { minSurfaceGap: number | null } {
  const gaps: number[] = [];
  rocks.forEach((a, i) => {
    for (const b of rocks.slice(i + 1)) {
      const gap = distance(a.position, b.position) - a.radius - b.radius;
      gaps.push(gap);
      if (gap < MIN_ROCK_SEPARATION) {
        out.push({
          rule: "separation",
          severity: "error",
          message:
            `${describe(a)}: surface gap ${fmt(gap)} to rock ${b.index} ` +
            `(${b.asteroidId}) at ${point(b.position)}, needs >= ${MIN_ROCK_SEPARATION}`,
          placementIndices: [a.index, b.index]
        });
      }
    }
  });
  return {
    minSurfaceGap: gaps.length > 0 ? gaps.reduce((m, g) => Math.min(m, g), Infinity) : null
  };
}

function checkVolumetric(
  arena: EditorArena,
  rocks: Rock[],
  yMin: number,
  yMax: number,
  out: Diagnostic[]
): void {
  const floorY = readFloorY(arena.bounds);
  const peak = rocks.reduce((best, r) => Math.max(best, Math.abs(r.position.y)), 0);

  if (floorY !== null) {
    // A floored arena has no space below its ground plane, so the two-sided
    // test is unsatisfiable by construction. The intent of the rule — "the map
    // uses the vertical axis" — survives as the one-sided reach above the
    // floor, measured with the same magnitude the rule already uses.
    const reach = yMax - floorY;
    out.push({
      rule: "volumetric",
      severity: "info",
      message:
        `arena declares a floor at y = ${fmt(floorY)}; the two-sided volumetric test ` +
        `(min y < -${VOLUMETRIC_SPAN}, max y > +${VOLUMETRIC_SPAN}) cannot apply, so rocks ` +
        `are required to reach >= ${VOLUMETRIC_PEAK} above the floor instead ` +
        `(highest rock is ${fmt(reach)} above it)`
    });
    if (reach < VOLUMETRIC_PEAK) {
      out.push({
        rule: "volumetric",
        severity: "error",
        message:
          `flat map: highest rock reaches only ${fmt(reach)} above the floor at ` +
          `y = ${fmt(floorY)}, needs >= ${VOLUMETRIC_PEAK}`
      });
    }
    return;
  }

  const failures: string[] = [];
  if (!(yMin < -VOLUMETRIC_SPAN)) {
    failures.push(`min y is ${fmt(yMin)}, needs < -${VOLUMETRIC_SPAN}`);
  }
  if (!(yMax > VOLUMETRIC_SPAN)) {
    failures.push(`max y is ${fmt(yMax)}, needs > +${VOLUMETRIC_SPAN}`);
  }
  if (!(peak >= VOLUMETRIC_PEAK)) {
    failures.push(`largest |y| is ${fmt(peak)}, needs >= ${VOLUMETRIC_PEAK}`);
  }
  if (failures.length > 0) {
    out.push({
      rule: "volumetric",
      severity: "error",
      message: `flat map: ${failures.join("; ")}`
    });
  }
}

function checkSpawnBounds(arena: EditorArena, out: Diagnostic[]): void {
  for (const sp of arena.spawnPoints) {
    const p = toVec3(sp.position);
    if (!isInsideBounds(p, arena.bounds)) {
      const detail =
        arena.bounds.shape === "sphere"
          ? `|P| = ${fmt(length(p))} exceeds bounds radius ${fmt(arena.bounds.radius)}`
          : `outside the ${fmt(arena.bounds.width)} × ${fmt(arena.bounds.height)} × ` +
            `${fmt(arena.bounds.verticalExtent)} box`;
      out.push({
        rule: "spawn-bounds",
        severity: "error",
        message: `spawn "${sp.id}" at ${point(p)} lies outside the arena bounds: ${detail}`,
        spawnIds: [sp.id]
      });
    }
  }
}

/**
 * Mirror symmetry is a *convention*, not a CI gate — an asymmetric map still
 * ships. So violations are warnings, and a map that is wholesale asymmetric
 * gets one summary line instead of a warning per rock: the author who
 * deliberately built an asymmetric arena should not have to dismiss thirty
 * diagnostics to see the real errors.
 */
function checkMirrorSymmetry(rocks: Rock[], out: Diagnostic[]): void {
  const sizeKey = (rock: Rock): string =>
    rock.radius === null ? `id:${rock.asteroidId}` : `r:${rock.radius.toFixed(6)}`;

  const untwinned = rocks.filter((rock) => {
    // A rock on the mirror plane is its own twin.
    if (Math.abs(rock.position.x) <= MIRROR_EPSILON) return false;
    return !rocks.some(
      (other) =>
        other.index !== rock.index &&
        sizeKey(other) === sizeKey(rock) &&
        Math.abs(other.position.x + rock.position.x) <= MIRROR_EPSILON &&
        Math.abs(other.position.y - rock.position.y) <= MIRROR_EPSILON &&
        Math.abs(other.position.z - rock.position.z) <= MIRROR_EPSILON
    );
  });

  if (untwinned.length === 0) return;

  if (untwinned.length * 2 > rocks.length) {
    out.push({
      rule: "mirror-symmetry",
      severity: "warning",
      message:
        `map is not mirror-symmetric in x: ${untwinned.length} of ${rocks.length} rocks ` +
        `have no twin at (-x, y, z) of the same size — reported once because the map ` +
        `reads as deliberately asymmetric`,
      placementIndices: untwinned.map((r) => r.index)
    });
    return;
  }

  for (const rock of untwinned) {
    out.push({
      rule: "mirror-symmetry",
      severity: "warning",
      message:
        `${describe(rock)}: no mirror twin — expected a same-size rock at ` +
        `${point({ x: -rock.position.x, y: rock.position.y, z: rock.position.z })}`,
      placementIndices: [rock.index]
    });
  }
}

function checkUnknownAsteroids(rocks: Rock[], out: Diagnostic[]): void {
  const byId = new Map<string, number[]>();
  for (const rock of rocks) {
    if (rock.radius !== null) continue;
    const indices = byId.get(rock.asteroidId) ?? [];
    indices.push(rock.index);
    byId.set(rock.asteroidId, indices);
  }
  for (const [asteroidId, indices] of byId) {
    out.push({
      rule: "unknown-asteroid",
      severity: "warning",
      message:
        `unknown asteroid id "${asteroidId}" (placement${indices.length > 1 ? "s" : ""} ` +
        `${indices.join(", ")}): collider radius is not known to the builder, so the ` +
        `extent, corridor, centrepiece and separation rules were skipped for ` +
        `${indices.length > 1 ? "these rocks" : "this rock"}. Ship an asteroid.* config ` +
        `for it and add its radius to the builder's palette`,
      placementIndices: indices
    });
  }
}

/**
 * Check an arena against the game's shipped-arena geometry rules.
 *
 * Pure: no DOM, no I/O, no mutation of the input — safe to call on every
 * keystroke and trivially unit-testable.
 *
 * Rules that cannot apply to the given map are *skipped with an info
 * diagnostic* rather than silently passing, so "ok" never hides an unasked
 * question: rect bounds skip the extent rule, a map with fewer than two teams
 * skips the corridor rule (and only that one — see the note at the call site),
 * an empty map skips every rock rule, and an unknown asteroid id skips only the
 * rules that need its radius.
 */
export function validateGeometry(arena: EditorArena): GeometryReport {
  const diagnostics: Diagnostic[] = [];
  const rocks = collectRocks(arena);
  const sized = rocks.filter(isSized);
  const { corridors, teamCount } = buildCorridors(arena);

  const ys = rocks.map((r) => r.position.y);
  const yMin = ys.length > 0 ? Math.min(...ys) : null;
  const yMax = ys.length > 0 ? Math.max(...ys) : null;

  checkWireLimit(arena, diagnostics);
  checkSpawnBounds(arena, diagnostics);
  checkUnknownAsteroids(rocks, diagnostics);

  if (rocks.length === 0) {
    diagnostics.push({
      rule: "placements",
      severity: "info",
      message: "arena has no asteroid placements; all rock geometry rules were skipped"
    });
  } else {
    checkExtent(arena, sized, diagnostics);

    if (corridors.length === 0) {
      diagnostics.push({
        rule: "corridor",
        severity: "info",
        message:
          `corridor checking needs two teams with spawn points; this arena has ` +
          `${teamCount}, so rule 2 was skipped`
      });
    } else {
      checkCorridor(corridors, sized, diagnostics);
    }

    // Rule 3 is deliberately NOT gated on team count. It measures a centrepiece
    // against each spawn pad individually, so it is fully defined for a
    // one-team map — and skipping it there would silently pass an arena with a
    // pad buried inside the centrepiece's collider, which is precisely the
    // failure the rule exists to catch. Only rule 2 needs two teams, because
    // only rule 2 needs a segment between them.
    checkCentrepieceClearance(arena, sized, diagnostics);

    if (yMin !== null && yMax !== null) {
      checkVolumetric(arena, rocks, yMin, yMax, diagnostics);
    }
    checkMirrorSymmetry(rocks, diagnostics);
  }

  const { minSurfaceGap } = checkSeparation(sized, diagnostics);

  // Stable sort: severity buckets keep the order the rules ran in, which is the
  // order an author reads the map in.
  diagnostics.sort((a, b) => SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity]);

  const stats: GeometryStats = {
    rockCount: rocks.length,
    centrepieceCount: sized.filter(isCentrepiece).length,
    unknownAsteroidCount: rocks.length - sized.length,
    minSurfaceGap,
    maxExtent:
      sized.length > 0
        ? sized.reduce((best, r) => Math.max(best, length(r.position) + r.radius), 0)
        : null,
    boundsRadius: arena.bounds.shape === "sphere" ? arena.bounds.radius : null,
    yMin,
    yMax,
    teamCount
  };

  return {
    ok: !diagnostics.some((d) => d.severity === "error"),
    diagnostics,
    stats
  };
}
